name: Build, Release, and Publish
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.20

      - name: Build Go package
        run: make build

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.20

      - name: Release to GitHub
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest

  publish-npm:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Set up NPM
        run: echo "//registry.npmjs.org/:_authToken=\${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish NPM package
        run: npm publish
