on:
  release:
    types: [created]
jobs:
    releases-matrix:
        name: Release Go Binary
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Install Node.js
          uses: actions/setup-node@v2
          with:
            node-version: 20.3.1
        - name: Set up Go
          uses: actions/setup-go@v2
          with:
            go-version: ^1.20.5
        - name: Install UPX
          run: | 
            curl -sfL https://github.com/upx/upx/releases/download/v4.0.2/upx-4.0.2-amd64_linux.tar.xz | tar -xJvf -;
            sudo mv upx-4.0.2-amd64_linux/upx /usr/local/bin;
            rm -rf upx-4.0.2-amd64_linux/
        - name: Build Go package
          run: make release
        - name: Upload release asset 
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ github.event.release.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
            asset_path: ./path/to/your/binary # Replace with the path to your binary
            asset_name: binary # Replace with the desired asset name
            asset_content_type: application/octet-stream
        